name: 'TEST CODE'
on: 

  workflow_dispatch:
jobs:
  build:
    name: 'Xem quá trình...'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Xem thông báo'
        run: |
          # Rom Rebuild
          export SIZE='8.5'; export URL='https://cdn-ota.azureedge.net/OS1.0.6.0.UMCCNXM/miui_FUXI_OS1.0.6.0.UMCCNXM_ded0db3571_14.0.zip'
          chmod -R 777 .github/bin/* >/dev/null
          export PATH="$GITHUB_WORKSPACE/.github/bin:$PATH"
          chmod -R 777 .github/*.sh >/dev/null
          bash .github/Test.sh
